### ISSUE TITLE
Intermittent struct error in message receive

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#123]
```
docker-compose -f dev.yml up --scale dev_worker=2
Creating ets_dev_pipeline ... done
Creating ets_dev_worker_1 ... done
Creating ets_dev_worker_2 ... done
Attaching to ets_dev_pipeline, ets_dev_worker_1, ets_dev_worker_2
dev_worker_2    | Traceback (most recent call last):
dev_worker_2    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_2    |     "__main__", mod_spec)
dev_worker_2    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_2    |     exec(code, run_globals)
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_2    |     dawgie.context._rev())
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_2    |     s = dawgie.security.connect (address)
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_2    |     _send (s, _recv (s))
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_2    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_2    | struct.error: unpack requires a buffer of 4 bytes
dev_worker_1    | Traceback (most recent call last):
dev_worker_1    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_1    |     "__main__", mod_spec)
dev_worker_1    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_1    |     exec(code, run_globals)
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_1    |     dawgie.context._rev())
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_1    |     s = dawgie.security.connect (address)
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_1    |     _send (s, _recv (s))
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_1    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_1    | struct.error: unpack requires a buffer of 4 bytes
```

**Comment by jpl-jengelke** [comment]
Note: This only occurs occasionally. Immediately after receiving this error the message did not appear on restart.

**Comment by al-niessner** [comment]
Socket timeouts at the server cause this error. Most common causes are pipeline is not in a state to receive new connections (prime twisted thread busy). Not enough backlog. Adding a delay between server and workers staring will probably do the trick.
