### ISSUE TITLE
Struct unpack error

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#137]
ETS using 1.2.12-rc01 is still sporadically getting the struct unpack error: 

```
Attaching to ets_dev_pipeline, ets_dev_worker_1, ets_dev_worker_4, ets_dev_worker_2, ets_dev_worker_3
dev_worker_1    | Traceback (most recent call last):
dev_worker_1    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_1    |     "__main__", mod_spec)
dev_worker_1    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_1    |     exec(code, run_globals)
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_1    |     dawgie.context._rev())
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_1    |     s = dawgie.security.connect (address)
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_1    |     _send (s, _recv (s))
dev_worker_1    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_1    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_1    | struct.error: unpack requires a buffer of 4 bytes
dev_worker_4    | Traceback (most recent call last):
dev_worker_4    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_4    |     "__main__", mod_spec)
dev_worker_4    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_4    |     exec(code, run_globals)
dev_worker_4    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_4    |     dawgie.context._rev())
dev_worker_4    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_4    |     s = dawgie.security.connect (address)
dev_worker_4    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_4    |     _send (s, _recv (s))
dev_worker_4    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_4    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_4    | struct.error: unpack requires a buffer of 4 bytes
dev_worker_3    | Traceback (most recent call last):
dev_worker_3    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_3    |     "__main__", mod_spec)
dev_worker_3    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_3    |     exec(code, run_globals)
dev_worker_3    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_3    |     dawgie.context._rev())
dev_worker_3    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_3    |     s = dawgie.security.connect (address)
dev_worker_3    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_3    |     _send (s, _recv (s))
dev_worker_3    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_3    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_3    | struct.error: unpack requires a buffer of 4 bytes
dev_worker_2    | Traceback (most recent call last):
dev_worker_2    |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
dev_worker_2    |     "__main__", mod_spec)
dev_worker_2    |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
dev_worker_2    |     exec(code, run_globals)
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 195, in <module>
dev_worker_2    |     dawgie.context._rev())
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 97, in execute
dev_worker_2    |     s = dawgie.security.connect (address)
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 207, in connect
dev_worker_2    |     _send (s, _recv (s))
dev_worker_2    |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 183, in _recv
dev_worker_2    |     l = struct.unpack ('>I', s.recv(4))[0]
dev_worker_2    | struct.error: unpack requires a buffer of 4 bytes
```

**Comment by jpl-jengelke** [comment]
Ideally, here is what would be desirable from this ticket: 

1. Error is captured and excepted as something like [ConnectionAbortedError](https://docs.python.org/3/library/exceptions.html#ConnectionAbortedError) with a reasonable explanation.
2. Some sort of wait is implemented to handle this type of connection error. 

Thanks.

**Comment by al-niessner** [comment]
Agreed that better messaging is desirable. dawgie.security._recv() should be expanded to do while loops over s.recv() to ensure it reads all of the desired data. This will cause the socket errors to become visible (rather than being hidden by the struct error). They should be caught and handled to indicate what the real error is like server not responding. To prevent infinite loops, it should not try again. Repeating and delays are the responsibility the layer that invokes dawgie.pl.worker as it has a world view consistent with the project. dawgie is supposed to be project independent and the delay/repeat needs for ETS are not the same as for EXCALIBUR.

The cause of this delay is known and was fixed on master branch for 1.3.0 but those changes cannot be moved back to 1.2.7. See #101 But, what should be a fix is not a substitute for better error messaging.

You are welcome to make the patch to the 1.2.x branch if you have the time.
