### ISSUE TITLE
sv render infinite loop?

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#143]
See ops.log.2020-07-2[567] for details. Need to build a test that duplicates this behavior then fix it.

Using grep, the problem has been around since since early September 2019.

```
2020-07-26 17:01:01,194 :: dawgie.fe.svrender :: ERROR :: Failed to complete a successful page: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dawgie/fe/svrender.py", line 82, in success
    try: self.__request.finish()
  File "/usr/local/lib/python3.6/dist-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.6/dist-packages/twisted/web/http.py", line 1080, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

**Comment by al-niessner** [comment]
This needs tested in isolation. Was the connection lost or was it satisfied but still get the message.

**Comment by al-niessner** [comment]
Ignoring until it becomes a problem again. Seems to be sporadic and real (requester kills connection).
