### ISSUE TITLE
Unhandled error in Deferred

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#158]
The on-disk data store prevents the application from restarting when some of its picled files are not present. There could be a number of error cases for the files being not present. However, it would be desirable for the application to non-destructively skip the missing data and resume. 

DAWGIE 1.12.13

"""
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 967, in runUntilCurrent
    f(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 662, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/state.py", line 338, in done
    def done(*_args, **_kwds): self.running_trigger()
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 1046, in _process
    return trigger()
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 259, in execute
    machine.callback(func, event_data)
  File "/usr/local/lib/python3.6/dist-packages/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/state.py", line 360, in navel_gaze
    (dawgie.db.metrics())
  File "/usr/local/lib/python3.6/dist-packages/dawgie/db/__init__.py", line 106, in metrics
    return _db_in_use().metrics()
  File "/usr/local/lib/python3.6/dist-packages/dawgie/db/post.py", line 803, in metrics
    msv[vn] = dawgie.db.util.decode(row[7])
  File "/usr/local/lib/python3.6/dist-packages/dawgie/db/util.py", line 57, in decode
    with open (os.path.join (dawgie.context.data_dbs, entry), 'rb') as f:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/proj/survey-ws/rt/dbs/5bdd90918497e34a52a11fb3ed6fd27c_1f6b4c67f953cad09fec5f3b77dffc12b8124bda'
"""

What caused this? Upon a power outage, the system was shut off abruptly (it is believed). That precise moment it seems a DB write stored a file handle but without pickle data on disk. Additionally, upon restart, the container was running but the app partially functioning. I believe the partially functioning app wrote to the relational DB but may have been unable to write to the on-disk data store. More than one of these missing file errors occurs. These file handles are in the relational DB (Postgres) but non-existent in the on-disk data store. 

Requests: 
1. Modify logging to record all file handle errors in a single log message. This provides a scope of the problem as it occurs rather than having to attempt file fixes and restart multiple times to learn that more than one file is missing. 
2. Relational DB inserts should only take place upon the file system write and the data integrity being verified. (This is unclear as of now, but a good practice.)
3. Recovery of metric/SV info should skip and mark the bad hashes as dirty in a sort of dead letter queue in case they are recovered later. This would allow the framework to restart and operate.

**Comment by jpl-jengelke** [comment]
This is not because of a missing mount or Docker deployment issue, it appears. This only affects certain files that are not there, and the system successfully reads files that it can see.

**Comment by al-niessner** [comment]
> What caused this?

The simple answer is that the database (postgres in this instance) diverged from the contents of your dbs.

Simple answer explained: To keep the database efficient, the large data blobs are not stored in the actual database. Therefore making the creation and storage of the data in dbs and the database an atomic transaction is not possible. Therefore the data is created in an staging area first then moved to dbs before an entry is created in the database for it. Having spare entries in the dbs is not a problem. Having entries in the database that are not in dbs is a problem and your specifically. How this can happen is a failure of a disk cache after the data has been moved but not physically written but the database has been updated. More simply, the files were removed by a user. Either way, this is a non-recoverable error without administrative help. In other words, there is no one set of solutions that fits all conditions. Hence, it just fails to get the attention of the adminstrator.

**Comment by jpl-jengelke** [comment]
Thanks Al, I have a question and a comment. 
- Is it possible the files are still in the staging area? Can they just be moved over?
- What I was thinking was something along the lines of the following code, please let me know if this is possible (excuse the pseudocode): 
```
    try: 
        create_large_data_blob
        file_name_hash = hash_of_large_data_blob
        copy_large_data_blob_into_dbs
        insert_into_database
    except DateInsertException as de: 
        log_error
        move_file_to_dead_letter_queue
        remove_file 
    except BaseException as be:
        log_error_unknown
        if_file_exists_in_dbs_move_to_dlq
    finally:
        if cursor: 
            cursor.close()
            del cursor
        if conn:
            conn.close()
            del conn
```
This way if the file write fails, the DB insert does not take place. If the DB insert fails, a zombie file is not left in place.

**Comment by al-niessner** [comment]
They may still be in staging but only because the file system failure allowed that to be the case. The code moves them not copies. Usually that is just an inode update which is far less expensive than copying and somewhat protected against loss just like you experienced.

The current code is what your pseudo code expresses already just without exceptions. If you consider for a moment how DAWGIE feeds state vectors into an algorithm then you should realize the gravest of problems is a reference in the database that no longer resolves to a real file in dbs. There is no way to workaround the problem of needing data that is not there.

**Comment by al-niessner** [comment]
> Modify logging to record all file handle errors in a single log message. This provides a scope of the problem as it occurs rather than having to attempt file fixes and restart multiple times to learn that more than one file is missing.

Logging treats each message as independent. There is no reason to treat them as groups except as in super specific conditions like this one. There is no way to tell if the file error is related to any other file error except by a human reading them and connecting them.

**Comment by al-niessner** [comment]
> Relational DB inserts should only take place upon the file system write and the data integrity being verified. (This is unclear as of now, but a good practice.)

It does exactly that. It cannot account for a write cache via network or hardware though. If you power outage is in that window then it will always fail.

**Comment by al-niessner** [comment]
> Recovery of metric/SV info should skip and mark the bad hashes as dirty in a sort of dead letter queue in case they are recovered later. This would allow the framework to restart and operate.

DAWGIE works on the concept of using its own creation. The metric state vectors are no different than any other state vector. Therefore if one that is referenced in the DB is missing in dbs then it is a critical failure and the whole concept of DAWGIE falls apart.

The difference about metric state vectors is that they are used during the navel gazing state when it self examines how data processing has occurred so that it can make decisions about what to run locally and what to run in the cloud. While you may not be exercising this aspect of DAWGIE it does not know that and tries to analyze what has been done before now and thus your failure.

**Comment by al-niessner** [comment]
Now, your best option is to restore a mildly older version from backup and then re-run from that base.

One aspect of DAWGIE that is not discussed much nor test much is that every time it goes to the idle state, it performs a database backup. They should be in your db directory (next to dbs). Restore the latest since it should not reference the data that you are missing. If it does for an even worse timing of the power outage, then go back one more version. There should be minimum of 10 but you can have more if you configure for it.
