### ISSUE TITLE
Scheduling not functioning as expected

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#44]
Setting a **schedule** with the following example source ... 
```def events():
    import ets.archive.scrape
    return [dawgie.EVENT(dawgie.ALG_REF(analysis, ets.archive.scrape.Analyzer()),
                         dawgie.MOMENT(None, '29', None, datetime.time(23, 45, 0)))]
```

Yields an exception ... 

```2019-08-29 16:37:26,475 :: root :: ERROR :: while loading the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/dist-packages/dawgie-1.2.5-py3.6.egg/dawgie/pl/state.py", line 237, in _pipeline
    dawgie.pl.schedule.periodics (facs[dawgie.Factories.events])
  File "/usr/local/lib/python3.6/dist-packages/dawgie-1.2.5-py3.6.egg/dawgie/pl/schedule.py", line 278, in periodics
    defer()
  File "/usr/local/lib/python3.6/dist-packages/dawgie-1.2.5-py3.6.egg/dawgie/pl/schedule.py", line 175, in defer
    ts = _delay (p).total_seconds()
  File "/usr/local/lib/python3.6/dist-packages/dawgie-1.2.5-py3.6.egg/dawgie/pl/schedule.py", line 96, in _delay
    return then - now
UnboundLocalError: local variable 'then' referenced before assignment```

Expected behavior: 

Scheduling executes tasks at indicated intervals.

**Comment by al-niessner** [comment]
Please use dawgie.schedule() to build dawgie.EVENTs for events() factories.
