### ISSUE TITLE
Concurrency issue in GnuPGP2 cleanup

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#69]
Note the `S.gpg-agent.extra` cleanup step at the bottom. I believe that DAWGIE is issuing a cleanup/delete command after the `python-gnupg` lib already performed an automatic cleanup of the file. The key here would be to introduce an atomic verify and delete-if-exists operation that is locking. Because this is on the file system, I think it would be difficult. Perhaps a better option is to delete if exists and then fail gracefully without error if it does not exist. The DAWGIE cleanup phase is at **line 213** in _security.py_: 

```
def finalize()->None:
    '''clean up after ones self

    Should be called when all done with the security module.
    '''
    shutil.rmtree (getattr (_pgp, gpgargname))
    return
```
Also worth noting is the [os.walk() option](https://docs.python.org/3/library/os.html#os.walk) which I believe is more resilient in terms of actually acting upon files the moment they are seen in the tree. 

I would ask for a simple solution, like altering the `shutil.rmtree()` call to be something like `shutil.rmtree(getattr (_pgp, gpgargname), ignore_errors=True)`. This has the cost of potentially not catching all errors but it also has the benefit of being applied in the narrow circumstances of pgp cleanup as the function is defined. 

> worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
worker_1  |     "__main__", mod_spec)
worker_1  |   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
worker_1  |     exec(code, run_globals)
worker_1  |   File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 196, in <module>
worker_1  |     finally: dawgie.security.finalize()
worker_1  |   File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 218, in finalize
worker_1  |     shutil.rmtree (getattr (_pgp, gpgargname))
worker_1  |   File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
worker_1  |     _rmtree_safe_fd(fd, path, onerror)
worker_1  |   File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
worker_1  |     onerror(os.unlink, fullname, sys.exc_info())
worker_1  |   File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
worker_1  |     os.unlink(name, dir_fd=topfd)
worker_1  | FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'
worker_1  | Timestamp of prior scrape is 2000-01-01 at 2019-12-04T12:11:36.86755

**Comment by jpl-jengelke** [comment]
Note please that this error is occurring frequently at the close of worker images (maybe 50 percent of the time), and it is confounding the error logs.

**Comment by jpl-jengelke** [comment]
Added fix per above. Closing.
