### ISSUE TITLE
restart bug

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#80]
One of the automated elements of dawgie is the process of updating the AE code without a reboot. The current process is being interrupted during the validation process with a logging error. Most importantly, within the security module:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 634, in emit
    self.send(s)
  File "/usr/lib/python3.6/logging/handlers.py", line 576, in send
    self.createSocket()
  File "/usr/lib/python3.6/logging/handlers.py", line 556, in createSocket
    self.sock = self.makeSocket()
  File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/logger/__init__.py", line 140, in makeSocket
    s = dawgie.security.connect (self.address)
  File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 206, in connect
    _send (s, message)
  File "/usr/local/lib/python3.6/dist-packages/dawgie/security.py", line 187, in _send
    signed = _pgp.sign (message, passphrase='1234567890', clearsign=True)
AttributeError: 'NoneType' object has no attribute 'sign'
```

**Comment by al-niessner** [comment]
Failure is coming from dawgie.tools.submit.auto_merge() because it is before the email. Since email says it failed, so the rest of the work is not done. When successful, it does the rest of the work of updating the DAG and such.
